config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "events#index"

  resources :events
  resources :users
  resources :invitations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :invitations, foreign_key: :created_event_id
  has_many :attendees, through: :invitations, source: :attendee
  belongs_to :creator, class_name: "User"

  scope :in_the_past, -> { where("date < ?", Date.current) }
  scope :in_the_future, -> { where("date > ?", Date.current) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :created_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :invitations, foreign_key: :attendee_id
  has_many :attended_events, through: :invitations, source: :created_event
  has_many :created_events, foreign_key: :creator_id, class_name: "Event"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def event_params
    params.require(:event).permit(:name, :date)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def new
    @invitation = Invitation.new
  end

  def create

    @invitation = current_user.invitations.build(invitation_params)

    if @invitation.save!
      redirect_to root_path,
      notice: "You've been added to this event's list of attendees."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def invitation_params
    params.require(:invitation).permit(:attendee_id, :created_event_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to new_user_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>Events</h1>

<h2>Past</h2>
<ul>
  <% @events.in_the_past.each do |past_event| %>
    <li>
      <p><%= link_to past_event.name, past_event %></p>
    </li>
  <% end %>
</ul>

<h2>Future</h2>
<ul>
  <% @events.in_the_future.each do |future_event| %>
  <li>
    <p><%= link_to future_event.name, future_event %>
  </li>
  <% end %>
</ul>

<%= button_to "New Event", new_event_path, :method => :get %>

app/views/events/new.html.erb
<%= form_with model: @event do |form| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being created:</h2>
      <ul>
        <% @event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.label :date %>
  <%= form.date_field :date %>
  <%= form.submit "Create Event" %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<p><%= @event.date %></p>

<h2>Attendees:</h2>

<ul>
  <% @event.attendees.each do |attendee| %>
    <li><%= attendee.email %></li>
  <% end %>
</ul>

<% if @event.attendees.include?(current_user) %>
  <%= "You've chosen to attend this event." %>
<% else%>
  <%= button_to "Attend Event", invitations_path,
        params: { invitation: { attendee_id: current_user.id, created_event_id: @event.id } },
        :method => :post %>
<% end %>

app/views/invitations/new.html.erb
<%= form_with model: @invitation do |form| %>
  <% if @invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitation.errors.count, "error") %> prohibited this invitation from being created:</h2>
      <ul>
        <% @invitation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.submit "Attend Event" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= link_to "Events", events_path %>
    <%= link_to "Users", users_path %>
    <%= link_to "View Profile", user_path(current_user.id) if current_user %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
    <p class="navbar-text float-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= button_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <p><%= link_to user.email, user %></p>
  <% end %>
</ul>

app/views/users/show.html.erb
<ul>
  <h3>Events Created</h3>
  <% if @user.created_events.empty? %>
    <%= "None" %>
  <% end %>
  <% @user.created_events.each do |created_event| %>
      <li><%= link_to created_event.name.capitalize, created_event %></li>
  <% end %>
  <%= button_to "Create Event", new_event_path, :method => :get %>
</ul>

<ul>
  <h3>Events Attended</h3>
  <h4>Past:</h3>
  <% @user.attended_events.in_the_past.each do |past_event| %>
    <li><%= link_to past_event.name.capitalize, past_event %></li>
  <% end %>

  <h4>Future:</h3>
  <% @user.attended_events.in_the_future.each do |future_event| %>
    <li><%= link_to future_event.name.capitalize, future_event %></li>
  <% end %>
  <%= button_to "Attend New Events", events_path, :method => :get %>
</ul>